fix `getAvailableSlotsAccelerator()`
In cases where the cmake variable `alpaka_ACC_GPU_CUDA_ONLY_MODE` is
false and the CUDA accelerator was used compile fails with:

```
/home/rwidera/workspace/mallocMC/src/include/mallocMC/device_allocator.hpp: In static member function ‘static unsigned int mallocMC::detail::GetAvailableSlotsIfAvailAcc<AlpakaAcc, T_Allocator, true>::getAvailableSlots(const AlpakaAcc&, size_t, T_Allocator&)’:
/home/rwidera/workspace/mallocMC/src/include/mallocMC/device_allocator.hpp:70:14: error: ‘CreationPolicy’ has not been declared
   70 |                 return alloc.T_Allocator::CreationPolicy::template getAvailableSlotsAccelerator<
      |              ^  ~~~~~~~~~~~
/home/rwidera/workspace/mallocMC/src/include/mallocMC/device_allocator.hpp:70:106: error: expected ‘(’ before ‘>’ token
   70 |                 return alloc.T_Allocator::CreationPolicy::template getAvailableSlotsAccelerator<
      |                                                                                                          ^
      |                                                                                                          (
```